name: StatsByRimon
version: '1.0-SNAPSHOT'
main: rimon.statsByRimon.StatsByRimon
api-version: '1.21'
depend: ["PlaceholderAPI"]

commands:
  Playerstats:
    Description: opens stats menu
    aliases:
      - stats
      - ps
    

